name: Create file
on:
  push
jobs:
  Create-empty-file:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Creating file"
      - run: touch sample.js
      - run: ls -lah
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Demo
          author_email: mail@example.com
          message: 'Your commit message'
          add: '*.js'
