name: Create file
on:
  push:
    branches:
      - test
      - !master
jobs:
  name: Create a empty file
  steps:
    - run: echo "Creating file"
    - run: touch sample.js
    - name: Commit changes
      uses: EndBug/add-and-commit@v7
      with:
        author_name: Your Name
        author_email: mail@example.com
        message: 'Your commit message'
        add: '*.js'
