name: Specific to a branch
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      - '!test'
  release:
    types: # This configuration does not affect the page_build event above
      - created