name: Add reviewer(s) and assignee for Pull requests.
on: push
jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Check for assignee
        run: echo "${{ github.event_name }}"

